### ISSUE TITLE
QIIME2 files to microtable?

### ISSUE THREAD

**Issue by kd-lab** [ChiLiubio/file2meco#2]
I tried to run the example that was provided and the output was:
> abund_file_path <- system.file("extdata", "dada2_table.qza", package="file2meco")
> sample_file_path <- system.file("extdata", "sample-metadata.tsv", package="file2meco")
> taxonomy_file_path <- system.file("extdata", "taxonomy.qza", package="file2meco")
> rep_fasta_path <- system.file("extdata", "dada2_rep_set.qza", package="file2meco")
> phylo_file_path <- system.file("extdata", "tree.qza", package="file2meco")
> qiime2meco(ASV_data = abund_file_path)
**Error in initialize(...) : unused argument (rep_fasta = NULL)**
> qiime2meco(ASV_data = abund_file_path, sample_data = sample_file_path, taxonomy_data = taxonomy_file_path)
**Error in initialize(...) : unused argument (rep_fasta = NULL)**
> qiime2meco(ASV_data = abund_file_path, sample_data = sample_file_path, taxonomy_data = taxonomy_file_path, phylo_tree = phylo_file_path, rep_fasta = rep_fasta_path)
**Error in FUN(X[[i]], ...) : 
  numbers of left and right parentheses in Newick string not equal**

I then tried to run it on my own files and got two different errors:
>**Error in initialize(...) : unused argument (rep_fasta = NULL)**
>**Error in initialize(...) : 
  unused argument (rep_fasta = list(c("t", "a", "c", "g", "g", "a", "g", "g", "a", "t", "c", "c", "g", "a", "g", "c", "g", "t", "t", "a", "t", "c", "c", "g", "g", "a", "t", "t", "t", "a", "t", "t", "g", "g", "g", "t", "t", "t", "a", "a", "a", "g", "g", "g", "a", "g", "c", "g", "t", "a", "g", "g", "t", "g", "g", "a", "c", "a", "g", "t", "t", "a", "a", "g", "t", "c", "a", "g", "t", "t", "g", "t", "g", "a", "a", "a", "g", "t", "t", "t", "g", "c", "g", "g", "c", "t", "c", "a", "a", "c", "c", "g", "t", "a", "a", 
"a", "a", "t", "t", "g", "c", "a", "g", "t", "t", "g", "a", "t", "a", "c", "t", "g", "g", "c", "t", "g", "t", "c", "t", "t", "g", "a", "g", "t", "a", "c", "a", "g", "t", "a", "g", "a", "g", "g", "t", "g", "g", "g", "c", "g", "g", "a", "a", "t", "t", "c", "g", "t", "g", "g"), c("t", "a", "c", "g", "g", "a", "g", "g", "a", "t", "c", "c", "g", "a", "g", "c", "g", "t", "t", "a", "t", "c", "c", "g", "g", "a", "t", "t", "t", "a", "t", "t", "g", "g", "g", "t", "t", "t", "a", "a",** 

Am I doing something wrong? I am a student and new to programming.

**Comment by ChiLiubio** [comment]
Hi,
What is your microeco version ?  Please reinstall microeco package using the steps shown in the README of file2meco. This issue may come from the old version of microeco package. Please try to install btoh the latest versions of microeco and file2meco in github.
