### ISSUE TITLE
Support for (Tree)SummarizedExperiment?

### ISSUE THREAD

**Issue by antagomir** [ChiLiubio/file2meco#21]
(Tree)SummarizedExperiment ([Huang et al. 2021](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7684683/)) is becoming increasingly common in microbiome data science in R/Bioconductor. Would it be possible to add support for this, like `treese2meco` or `se2meco` function?

**Comment by ChiLiubio** [comment]
Thanks for the suggestion! We will have a try.

Best,
Chi

**Comment by antagomir** [comment]
Keep us posted, we would have use for it!

**Comment by ChiLiubio** [comment]
Hi. I have added tse2meco and meco2tse function in github. If you need them, you can reinstall the package from github and have a try. Please feel free to tell me if the function donot work well.

**Comment by antagomir** [comment]
Thanks, we will test!

**Comment by antagomir** [comment]
Ok seems good. I have opened an issue elsewhere and we will consider how to incorporate more tightly with TreeSE microbiome resources.

**Comment by ChiLiubio** [comment]
Great! I will pay attention to it.
