### ISSUE TITLE
Conversion between microtable and phyloseq

### ISSUE THREAD

**Issue by kbitenieks** [ChiLiubio/file2meco#3]
Hi,

I made a full microtable, but after the conversion the phyloseq object have lost one sample and representative sequences (all slot is lost).
What might be the problem?

**Comment by ChiLiubio** [comment]
Hi,
Do you make sure the sample names between sample table and otu table are corresponding? Please check it using tidy_dataset function in microtable class.
I remember there is no slot to store the sequences in phyloseq class.

**Comment by kbitenieks** [comment]
Yes, the sample names are the same. I assume it is because this sample contains no sequences (it's a negative control).
