### ISSUE TITLE
deseq2 to microtable

### ISSUE THREAD

**Issue by ShailNair** [ChiLiubio/file2meco#5]
Hi,
Is it possible to convert deseq2 output to microecotable format for analysis in microeco?

**Comment by ChiLiubio** [comment]
Hi,
Do you mean the differential gene output format in deseq2? or other format? Could you please send me an example data to make it clear?

Chi

**Comment by razz1618** [comment]
yes..the DG output.. i guess the normal Deseq2 output may not be able to use here, which looks like this:

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File href="file:///C:/conda_tmp/msohtmlclip1/01/clip.htm">
<link rel=File-List href="file:///C:/conda_tmp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



baseMean | log2FoldChange | lfcSE | stat | pvalue | padj |  
-- | -- | -- | -- | -- | -- | --
K03722 | 15295.72 | 7.034358 | 0.397316 | 17.70471 | 3.86E-70 | 2.03E-66
K21471 | 3011.469 | 7.819785 | 0.466552 | 16.7608 | 4.72E-63 | 1.24E-59
K08762 | 1744.846 | 7.912253 | 0.48321 | 16.37436 | 2.92E-60 | 5.12E-57
K10108 | 2917.268 | 9.835202 | 0.602285 | 16.3298 | 6.06E-60 | 7.97E-57
K13688 | 4724.166 | 6.970871 | 0.457688 | 15.23062 | 2.21E-52 | 2.33E-49
K00796 | 68821.04 | 7.212689 | 0.540775 | 13.33769 | 1.40E-40 | 1.23E-37
K03238 | 737.9924 | 6.723505 | 0.504655 | 13.32298 | 1.70E-40 | 1.28E-37
K04763 | 55848.72 | 7.062034 | 0.542101 | 13.02716 | 8.57E-39 | 5.64E-36
K07260 | 1176.871 | 4.547297 | 0.405763 | 11.20678 | 3.78E-29 | 2.08E-26



</body>

</html>


but a Transformed matrix like this:
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File href="file:///C:/conda_tmp/msohtmlclip1/01/clip.htm">
<link rel=File-List href="file:///C:/conda_tmp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



gene | s1.1 | s1.2 | s2.1 | s2.2
-- | -- | -- | -- | --
K00002 | 10.38523 | 10.38038 | 9.118427 | 9.922559
K00003 | 9.678345 | 9.769272 | 9.619521 | 10.08289
K00004 | 5.362051 | 5.160816 | 4.251707 | 4.711154
K00005 | 4.140037 | 3.735243 | 9.659916 | 9.067583
K00008 | 5.912784 | 6.611608 | 4.872427 | 5.629285
K00009 | 4.558262 | 4.622016 | 4.717109 | 3.614935
K00010 | 9.030268 | 8.98283 | 7.809744 | 10.03238
K00012 | 12.70024 | 12.71699 | 11.54834 | 11.83476
K00013 | 9.577841 | 9.440944 | 10.059 | 10.29607
K00014 | 8.451744 | 8.298778 | 10.37431 | 9.309811
K00015 | 9.130081 | 9.070013 | 10.17155 | 10.01613
K00016 | 10.57328 | 10.45589 | 6.739647 | 6.819845
K00018 | 4.140037 | 5.078077 | 5.737196 | 6.130415



</body>

</html>

maybe able to use under microeco? can we? Usually, the graphical representation of the second table would look like this (cell labels are just for reference purpose and does not match with the above table):

![fwf](https://user-images.githubusercontent.com/59241611/129119437-d0931863-5672-4814-8fa5-9f4ea4555a99.png)

**Comment by ChiLiubio** [comment]
Yes. The second transformed table can be used as input in microeco. Though the first table can not be used directly, it is can be provided as input files in some functions to select the important biomarkers.

**Comment by razz1618** [comment]
Thanks.

**Comment by ChiLiubio** [comment]
Hi @razz1618 

Actually, I have the idea to add the method in DESeq2 (maybe also edgeR) to the microeco package before. Thus, it is easy to use this famous method and the following plotting. However, maintaining such project is hard work. So it is on hold today. If you are interested in this part of work, we can discuss this and cooperate to do it. Please feel free to tell me if you have any idea. My email:  liuchi0426@126.com

Best wishes
Chi
