### ISSUE TITLE
phyloseq2meco

### ISSUE THREAD

**Issue by mtva0001** [ChiLiubio/file2meco#7]
Hi, 

I got this error:
Error in tax_table_trans %<>% tidy_taxonomy : 
  lazy-load database '/Library/Frameworks/R.framework/Versions/4.0/Resources/library/microeco/R/microeco.rdb' is corrupt
In addition: Warning messages:
1: In tax_table_trans %<>% tidy_taxonomy :
  restarting interrupted promise evaluation
2: In tax_table_trans %<>% tidy_taxonomy :
  internal error -3 in R_decompress1

Why is it happening?:(

**Comment by ChiLiubio** [comment]
Hi,

I think the microeco package may be installed with some issues. Please first manually delete the installation directory (/Library/Frameworks/R.framework/Versions/4.0/Resources/library/microeco) and then try to install it again from CRAN.

Chi

**Comment by mtva0001** [comment]
Thanks! It worked!
