### ISSUE TITLE
after transferring QIIME2 files to microtable, how can I make the file as the dataset, which is used in the downstream analyse?

### ISSUE THREAD

**Issue by yezi0721** [ChiLiubio/file2meco#9]
after transferring QIIME2 files to microtable, how can I make the file as the dataset, which is used in the downstream analyse?

**Comment by ChiLiubio** [comment]
Hi. What is your meaning of "as the dataset"? The microtable object is the dataset that used in all the downstream analysis.

```
your_dataset <- qiime2meco(ASV_data = abund_file_path, sample_data = sample_file_path, taxonomy_data = taxonomy_file_path)
your_dataset
# use ?microtable or other class to see the functions
```

**Comment by yezi0721** [comment]
懂了，谢谢~
